export const PreferenceData = [
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "Marketing Automation",
    company: "Idea Usher ",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "19,000",
    monthLogo: "",
    month: " 7 Months",
  },
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "Wordpress Development",
    company: "Zyla",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "14,000",
    monthLogo: "",
    month: " 4 Months",
  },
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "UI Development",
    company: "Yars Enterprizez",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "8,000",
    monthLogo: "",
    month: " 8 Months",
  },
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "Product  Support Engineering",
    company: "Right Angel",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "12,000",
    monthLogo: "",
    month: " 2 Months",
  },
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "Fronted Development",
    company: "India AI development",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "11,000",
    monthLogo: "",
    month: " 4 Months",
  },
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "Backend Developer",
    company: "Callous Private Limited",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "15,000",
    monthLogo: "",
    month: " 3 Months",
  },
  {
    logo: "Actively hiring",
    imge: "growth.png",
    job: "Fullstack Development",
    company: "IT Solution",
    logo1: "",
    location: "Work From Home",
    moneyLogo: "",
    sallary: "12,000",
    monthLogo: "",
    month: " 4 Months",
  },
];
